#!/usr/bin/env python3
"""
Stingray ingestion layer — live weather field fetcher (prototype).

Pulls a 31-hour wind + wave forecast grid for the western Mediterranean
(Antibes -> Porto Cervo corridor) via the Open-Meteo forecast and marine
APIs (model data originates from ECMWF/NOAA/MeteoFrance wave models; no
API key required), and writes it as `../livewx.js`, which the passage
planner auto-detects and offers as a "Live" scenario.

Production path: fetch raw GRIB2 directly from NOAA NOMADS instead —
see fetch_grib_nomads.py. This JSON-grid route is the low-friction demo
equivalent of the corrected-GRIB pipeline described in the architecture.

Usage:  python3 fetch_weather.py
Stdlib only — no dependencies.
"""
import json, urllib.request, urllib.parse, datetime, sys, os

# Grid matches the planner's map window
LAT0, LAT1, LON0, LON1, STEP = 40.75, 44.0, 6.7, 10.15, 0.25
HOURS = 31          # matches the planner's forecast scrub (+0..30h)
CHUNK = 50          # points per API request
MS_TO_KN = 1.94384

def grid_points():
    lats, lons = [], []
    la = LAT0
    while la <= LAT1 + 1e-9:
        lo = LON0
        while lo <= LON1 + 1e-9:
            lats.append(round(la, 3)); lons.append(round(lo, 3))
            lo += STEP
        la += STEP
    return lats, lons

def api(base, lats, lons, hourly, extra=""):
    """Chunked multi-point request; returns list of per-point hourly dicts."""
    out = []
    for i in range(0, len(lats), CHUNK):
        q = (f"latitude={','.join(map(str,lats[i:i+CHUNK]))}"
             f"&longitude={','.join(map(str,lons[i:i+CHUNK]))}"
             f"&hourly={hourly}&forecast_days=3&timezone=UTC{extra}")
        with urllib.request.urlopen(f"{base}?{q}", timeout=60) as r:
            data = json.loads(r.read())
        out += data if isinstance(data, list) else [data]
        print(f"  {base.split('/')[2]}: {min(i+CHUNK,len(lats))}/{len(lats)} points")
    return out

def series(pt, key, scale=1.0, fill=0.0):
    vals = (pt.get("hourly") or {}).get(key) or []
    return [ (v*scale if v is not None else fill) for v in vals[:HOURS] ]

def main():
    lats, lons = grid_points()
    nlat = len(set(lats)); nlon = len(set(lons))
    print(f"Fetching {nlat}x{nlon} grid, {HOURS}h horizon...")
    wind = api("https://api.open-meteo.com/v1/forecast", lats, lons,
               "wind_speed_10m,wind_direction_10m", "&wind_speed_unit=kn")
    wave = api("https://marine-api.open-meteo.com/v1/marine", lats, lons,
               "wave_height,wave_direction")

    def cube(points, key, scale=1.0, fill=0.0):
        # -> [t][iy][ix]
        c = []
        for t in range(HOURS):
            plane = []
            for iy in range(nlat):
                row = []
                for ix in range(nlon):
                    s = series(points[iy*nlon+ix], key, scale, fill)
                    row.append(round(s[t] if t < len(s) else fill, 2))
                plane.append(row)
            c.append(plane)
        return c

    field = {
        "source": "Open-Meteo (ECMWF/NOAA wave models)",
        "fetched": datetime.datetime.utcnow().isoformat(),
        "lat0": LAT0, "lon0": LON0, "dlat": STEP, "dlon": STEP,
        "nlat": nlat, "nlon": nlon,
        "hours": list(range(HOURS)),
        "hs":      cube(wave, "wave_height"),          # m   (0 over land)
        "wavedir": cube(wave, "wave_direction"),       # deg (from)
        "wspd":    cube(wind, "wind_speed_10m"),       # kn
        "wdir":    cube(wind, "wind_direction_10m"),   # deg (from)
    }
    out = os.path.join(os.path.dirname(__file__), "..", "livewx.js")
    with open(out, "w") as f:
        f.write("// Generated by ingest/fetch_weather.py — do not edit\n")
        f.write("const LIVE_WX=" + json.dumps(field, separators=(",", ":")) + ";\n")
        f.write('if(typeof window!=="undefined")window.LIVE_WX=LIVE_WX;\n')
        f.write('if(typeof module!=="undefined")module.exports=LIVE_WX;\n')
    print(f"Wrote {os.path.abspath(out)} ({os.path.getsize(out)//1024} KB)")

if __name__ == "__main__":
    sys.exit(main())
